version: '3'
services:
  spider:
    image: bonianahao/spider:1.0.1
    ports:
      - "5010:5010"
    environment:
      DB_CONN: "redis://192.168.100.78:6379/0"  # Use the service name and port of the redis container

  redis:
    image: redis:6.0.6
    ports:
      - "6666:6379"
